project_id = "agndhravgmcwpdjkozka"

[functions.send_message]
verify_jwt = false

[functions.send_reply]
verify_jwt = false

[functions.n8n-control]
verify_jwt = true

[functions.n8n-agent-webhook]
verify_jwt = false
